import { PT_Serif } from 'next/font/google';

const font = PT_Serif({ weight: '400', subsets: ['latin'], display: 'swap' });
import '../../globals.css';
import Box from '@mui/material/Box';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const borderSize = 0;

export default function RootLayout({ children }) {
  return <>{children}</>;
}
