import { PT_Serif } from 'next/font/google';

const font = PT_Serif({ weight: '400', subsets: ['latin'], display: 'swap' });
import './globals.css';
import Box from '@mui/material/Box';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const borderSize = 0;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://esm.sh/@wooorm/starry-night@3/style/both"
        />
      </head>
      <body className={font.className}>
        <Box
          sx={{
            margin: 0,
            display: 'flex',
            flex: 1,
            justifyContent: 'center',
            justifyItems: 'center',
            alignItems: 'center',
            alignContent: 'center'
          }}
        >
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              border: borderSize,
              margin: 0,
              padding: 0,
              minHeight: '100vh',
              minWidth: '1024px',
              maxWidth: '1024px'
            }}
          >
            <Box
              sx={{
                flex: 'initial',
                border: borderSize,
                padding: 3,
                margin: 0,
                backgroundColor: '#303030',
                borderRadius: 3
              }}
            >
              <Box
                sx={{
                  fontWeight: 'bold',
                  fontSize: '2rem',
                  color: 'white'
                }}
              >
                thefourtheye's weblog
              </Box>
              <Box
                sx={{
                  fontWeight: 'normal',
                  fontSize: '1rem',
                  color: '#9A9A9A'
                }}
              >
                opinions are my own; try code/suggestions at your own risk
              </Box>
            </Box>
            <Box
              sx={{
                flex: 1,
                border: borderSize,
                padding: 0,
                margin: 0,
                overflow: 'auto'
              }}
            >
              {children}
            </Box>
            <Box
              sx={{
                flex: 'initial',
                borderRadius: 3,
                border: borderSize,
                padding: 3,
                margin: 0,
                backgroundColor: '#303030',
                color: '#9A9A9A'
              }}
            >
              Copyright © 2024 - Sakthipriyan Vairamani (thefourtheye)
            </Box>
          </Box>
        </Box>
      </body>
    </html>
  );
}
